PROGRAM FACTORIAL

    REAL(16) :: VALUE
    READ *, VALUE
    VALUE = FAC(VALUE)
    WRITE(*, *) 'RESULT: ', VALUE

    CONTAINS 

    RECURSIVE FUNCTION FAC(INPUT) RESULT(OUTPUT)
        IMPLICIT NONE
        REAL(16), INTENT(IN) :: INPUT
        REAL(16) :: OUTPUT
        IF((INPUT.EQ.1).OR.(INPUT.EQ.0)) THEN
            OUTPUT = 1
            ELSE
            OUTPUT = INPUT * FAC(INPUT - 1)
        END IF
    END FUNCTION FAC
END PROGRAM FACTORIAL
