PROGRAM SQRT_APPROACH

    IMPLICIT NONE
    REAL(16) :: VALUE, X1, X2

    READ *, VALUE

    X1 = (VALUE + (VALUE / VALUE)) / 2
    
100 X2 = (X1 + (VALUE / X1)) / 2
    IF (.NOT.(X1.EQ.X2)) THEN
        X1 = (X2 + (VALUE / X2)) / 2
        GO TO 100
    ELSE
        WRITE (*, *) 'O RESULTADO APROXIMADO DA RAIZ E:', X1
    END IF

END PROGRAM SQRT_APPROACH